security:
  oauth2:
    client:
      clientId: account-service
      clientSecret: ${ACCOUNT_SERVICE_PASSWORD}
      accessTokenUri: http://auth-service:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      host: 114.118.13.147
      username: user
      password: qwert54321
      database: piggy
      port: 9017

server:
  context-path: /accounts
  port: 6000

